version: '3.7'
services:

  node:
    build:
      context: .
      dockerfile: gate-simulator/Dockerfile
    container_name: node-container
    working_dir: /home/node/app
    volumes:
      - ./gate-simulator:/home/node/app
    ports:
      - '9999:9999'

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - '3306:3306'
    volumes:
      - ./db/data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:latest
    container_name: postgresql-container
    ports:
      - '5432:5432'
    volumes:
      - ./db/data_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass





